spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/felizvitoz/tadi-config.git
          searchPaths: /config
          refreshRate: 60

server:
  port: 8889