spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 25
    url: jdbc:postgresql://docker-compose-postgresql-1:5440/redemption_apps
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  application:
    jpa:
      show-sql: true